use self::Isotope::*;
use crate::{
    isotopes::{
        Ac, Ag, Al, Am, Ar, As, At, Au, Ba, Be, Bh, Bi, Bk, Br, Ca, Cd, Ce, Cf, Cl, Cm, Cn, Co, Cr,
        Cs, Cu, Db, Ds, Dy, Er, Es, Eu, Fe, Fl, Fm, Fr, Ga, Gd, Ge, He, Hf, Hg, Ho, Hs, In, Ir, Kr,
        La, Li, Lr, Lu, Lv, Mc, Md, Mg, Mn, Mo, Mt, Na, Nb, Nd, Ne, Nh, Ni, No, Np, Og, Os, Pa, Pb,
        Pd, Pm, Po, Pr, Pt, Pu, Ra, Rb, Re, Rf, Rg, Rh, Rn, Ru, Sb, Sc, Se, Sg, Si, Sm, Sn, Sr, Ta,
        Tb, Tc, Te, Th, Ti, Tl, Tm, Ts, Xe, Yb, Zn, Zr, B, C, F, H, I, K, N, O, P, S, U, V, W, Y,
    },
    Element, Error, Result, Uncertain,
};
use derive_more::From;
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};
use std::str::FromStr;
use strum::IntoEnumIterator;

/// Isotope
#[derive(Clone, Copy, Debug, Eq, From, Hash, Ord, PartialEq, PartialOrd)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum Isotope {
    H(H),
    He(He),
    Li(Li),
    Be(Be),
    B(B),
    C(C),
    N(N),
    O(O),
    F(F),
    Ne(Ne),
    Na(Na),
    Mg(Mg),
    Al(Al),
    Si(Si),
    P(P),
    S(S),
    Cl(Cl),
    Ar(Ar),
    K(K),
    Ca(Ca),
    Sc(Sc),
    Ti(Ti),
    V(V),
    Cr(Cr),
    Mn(Mn),
    Fe(Fe),
    Co(Co),
    Ni(Ni),
    Cu(Cu),
    Zn(Zn),
    Ga(Ga),
    Ge(Ge),
    As(As),
    Se(Se),
    Br(Br),
    Kr(Kr),
    Rb(Rb),
    Sr(Sr),
    Y(Y),
    Zr(Zr),
    Nb(Nb),
    Mo(Mo),
    Tc(Tc),
    Ru(Ru),
    Rh(Rh),
    Pd(Pd),
    Ag(Ag),
    Cd(Cd),
    In(In),
    Sn(Sn),
    Sb(Sb),
    Te(Te),
    I(I),
    Xe(Xe),
    Cs(Cs),
    Ba(Ba),
    La(La),
    Ce(Ce),
    Pr(Pr),
    Nd(Nd),
    Pm(Pm),
    Sm(Sm),
    Eu(Eu),
    Gd(Gd),
    Tb(Tb),
    Dy(Dy),
    Ho(Ho),
    Er(Er),
    Tm(Tm),
    Yb(Yb),
    Lu(Lu),
    Hf(Hf),
    Ta(Ta),
    W(W),
    Re(Re),
    Os(Os),
    Ir(Ir),
    Pt(Pt),
    Au(Au),
    Hg(Hg),
    Tl(Tl),
    Pb(Pb),
    Bi(Bi),
    Po(Po),
    At(At),
    Rn(Rn),
    Fr(Fr),
    Ra(Ra),
    Ac(Ac),
    Th(Th),
    Pa(Pa),
    U(U),
    Np(Np),
    Pu(Pu),
    Am(Am),
    Cm(Cm),
    Bk(Bk),
    Cf(Cf),
    Es(Es),
    Fm(Fm),
    Md(Md),
    No(No),
    Lr(Lr),
    Rf(Rf),
    Db(Db),
    Sg(Sg),
    Bh(Bh),
    Hs(Hs),
    Mt(Mt),
    Ds(Ds),
    Rg(Rg),
    Cn(Cn),
    Nh(Nh),
    Fl(Fl),
    Mc(Mc),
    Lv(Lv),
    Ts(Ts),
    Og(Og),
}

impl Isotope {
    /// Element
    #[must_use]
    pub const fn element(&self) -> Element {
        match self {
            H(_) => Element::H,
            He(_) => Element::He,
            Li(_) => Element::Li,
            Be(_) => Element::Be,
            B(_) => Element::B,
            C(_) => Element::C,
            N(_) => Element::N,
            O(_) => Element::O,
            F(_) => Element::F,
            Ne(_) => Element::Ne,
            Na(_) => Element::Na,
            Mg(_) => Element::Mg,
            Al(_) => Element::Al,
            Si(_) => Element::Si,
            P(_) => Element::P,
            S(_) => Element::S,
            Cl(_) => Element::Cl,
            Ar(_) => Element::Ar,
            K(_) => Element::K,
            Ca(_) => Element::Ca,
            Sc(_) => Element::Sc,
            Ti(_) => Element::Ti,
            V(_) => Element::V,
            Cr(_) => Element::Cr,
            Mn(_) => Element::Mn,
            Fe(_) => Element::Fe,
            Co(_) => Element::Co,
            Ni(_) => Element::Ni,
            Cu(_) => Element::Cu,
            Zn(_) => Element::Zn,
            Ga(_) => Element::Ga,
            Ge(_) => Element::Ge,
            As(_) => Element::As,
            Se(_) => Element::Se,
            Br(_) => Element::Br,
            Kr(_) => Element::Kr,
            Rb(_) => Element::Rb,
            Sr(_) => Element::Sr,
            Y(_) => Element::Y,
            Zr(_) => Element::Zr,
            Nb(_) => Element::Nb,
            Mo(_) => Element::Mo,
            Tc(_) => Element::Tc,
            Ru(_) => Element::Ru,
            Rh(_) => Element::Rh,
            Pd(_) => Element::Pd,
            Ag(_) => Element::Ag,
            Cd(_) => Element::Cd,
            In(_) => Element::In,
            Sn(_) => Element::Sn,
            Sb(_) => Element::Sb,
            Te(_) => Element::Te,
            I(_) => Element::I,
            Xe(_) => Element::Xe,
            Cs(_) => Element::Cs,
            Ba(_) => Element::Ba,
            La(_) => Element::La,
            Ce(_) => Element::Ce,
            Pr(_) => Element::Pr,
            Nd(_) => Element::Nd,
            Pm(_) => Element::Pm,
            Sm(_) => Element::Sm,
            Eu(_) => Element::Eu,
            Gd(_) => Element::Gd,
            Tb(_) => Element::Tb,
            Dy(_) => Element::Dy,
            Ho(_) => Element::Ho,
            Er(_) => Element::Er,
            Tm(_) => Element::Tm,
            Yb(_) => Element::Yb,
            Lu(_) => Element::Lu,
            Hf(_) => Element::Hf,
            Ta(_) => Element::Ta,
            W(_) => Element::W,
            Re(_) => Element::Re,
            Os(_) => Element::Os,
            Ir(_) => Element::Ir,
            Pt(_) => Element::Pt,
            Au(_) => Element::Au,
            Hg(_) => Element::Hg,
            Tl(_) => Element::Tl,
            Pb(_) => Element::Pb,
            Bi(_) => Element::Bi,
            Po(_) => Element::Po,
            At(_) => Element::At,
            Rn(_) => Element::Rn,
            Fr(_) => Element::Fr,
            Ra(_) => Element::Ra,
            Ac(_) => Element::Ac,
            Th(_) => Element::Th,
            Pa(_) => Element::Pa,
            U(_) => Element::U,
            Np(_) => Element::Np,
            Pu(_) => Element::Pu,
            Am(_) => Element::Am,
            Cm(_) => Element::Cm,
            Bk(_) => Element::Bk,
            Cf(_) => Element::Cf,
            Es(_) => Element::Es,
            Fm(_) => Element::Fm,
            Md(_) => Element::Md,
            No(_) => Element::No,
            Lr(_) => Element::Lr,
            Rf(_) => Element::Rf,
            Db(_) => Element::Db,
            Sg(_) => Element::Sg,
            Bh(_) => Element::Bh,
            Hs(_) => Element::Hs,
            Mt(_) => Element::Mt,
            Ds(_) => Element::Ds,
            Rg(_) => Element::Rg,
            Cn(_) => Element::Cn,
            Nh(_) => Element::Nh,
            Fl(_) => Element::Fl,
            Mc(_) => Element::Mc,
            Lv(_) => Element::Lv,
            Ts(_) => Element::Ts,
            Og(_) => Element::Og,
        }
    }

    /// Composition
    #[must_use]
    pub const fn isotopic_composition(&self) -> Option<Uncertain> {
        match self {
            H(h) => h.isotopic_composition(),
            He(he) => he.isotopic_composition(),
            Li(li) => li.isotopic_composition(),
            Be(be) => be.isotopic_composition(),
            B(b) => b.isotopic_composition(),
            C(c) => c.isotopic_composition(),
            N(n) => n.isotopic_composition(),
            O(o) => o.isotopic_composition(),
            F(f) => f.isotopic_composition(),
            Ne(ne) => ne.isotopic_composition(),
            Na(na) => na.isotopic_composition(),
            Mg(mg) => mg.isotopic_composition(),
            Al(al) => al.isotopic_composition(),
            Si(si) => si.isotopic_composition(),
            P(p) => p.isotopic_composition(),
            S(s) => s.isotopic_composition(),
            Cl(cl) => cl.isotopic_composition(),
            Ar(ar) => ar.isotopic_composition(),
            K(k) => k.isotopic_composition(),
            Ca(ca) => ca.isotopic_composition(),
            Sc(sc) => sc.isotopic_composition(),
            Ti(ti) => ti.isotopic_composition(),
            V(v) => v.isotopic_composition(),
            Cr(cr) => cr.isotopic_composition(),
            Mn(mn) => mn.isotopic_composition(),
            Fe(fe) => fe.isotopic_composition(),
            Co(co) => co.isotopic_composition(),
            Ni(ni) => ni.isotopic_composition(),
            Cu(cu) => cu.isotopic_composition(),
            Zn(zn) => zn.isotopic_composition(),
            Ga(ga) => ga.isotopic_composition(),
            Ge(ge) => ge.isotopic_composition(),
            As(r#as) => r#as.isotopic_composition(),
            Se(se) => se.isotopic_composition(),
            Br(br) => br.isotopic_composition(),
            Kr(kr) => kr.isotopic_composition(),
            Rb(rb) => rb.isotopic_composition(),
            Sr(sr) => sr.isotopic_composition(),
            Y(y) => y.isotopic_composition(),
            Zr(zr) => zr.isotopic_composition(),
            Nb(nb) => nb.isotopic_composition(),
            Mo(mo) => mo.isotopic_composition(),
            Tc(tc) => tc.isotopic_composition(),
            Ru(ru) => ru.isotopic_composition(),
            Rh(rh) => rh.isotopic_composition(),
            Pd(pd) => pd.isotopic_composition(),
            Ag(ag) => ag.isotopic_composition(),
            Cd(cd) => cd.isotopic_composition(),
            In(r#in) => r#in.isotopic_composition(),
            Sn(sn) => sn.isotopic_composition(),
            Sb(sb) => sb.isotopic_composition(),
            Te(te) => te.isotopic_composition(),
            I(i) => i.isotopic_composition(),
            Xe(xe) => xe.isotopic_composition(),
            Cs(cs) => cs.isotopic_composition(),
            Ba(ba) => ba.isotopic_composition(),
            La(la) => la.isotopic_composition(),
            Ce(ce) => ce.isotopic_composition(),
            Pr(pr) => pr.isotopic_composition(),
            Nd(nd) => nd.isotopic_composition(),
            Pm(pm) => pm.isotopic_composition(),
            Sm(sm) => sm.isotopic_composition(),
            Eu(eu) => eu.isotopic_composition(),
            Gd(gd) => gd.isotopic_composition(),
            Tb(tb) => tb.isotopic_composition(),
            Dy(dy) => dy.isotopic_composition(),
            Ho(ho) => ho.isotopic_composition(),
            Er(er) => er.isotopic_composition(),
            Tm(tm) => tm.isotopic_composition(),
            Yb(yb) => yb.isotopic_composition(),
            Lu(lu) => lu.isotopic_composition(),
            Hf(hf) => hf.isotopic_composition(),
            Ta(ta) => ta.isotopic_composition(),
            W(w) => w.isotopic_composition(),
            Re(re) => re.isotopic_composition(),
            Os(os) => os.isotopic_composition(),
            Ir(ir) => ir.isotopic_composition(),
            Pt(pt) => pt.isotopic_composition(),
            Au(au) => au.isotopic_composition(),
            Hg(hg) => hg.isotopic_composition(),
            Tl(tl) => tl.isotopic_composition(),
            Pb(pb) => pb.isotopic_composition(),
            Bi(bi) => bi.isotopic_composition(),
            Po(po) => po.isotopic_composition(),
            At(at) => at.isotopic_composition(),
            Rn(rn) => rn.isotopic_composition(),
            Fr(fr) => fr.isotopic_composition(),
            Ra(ra) => ra.isotopic_composition(),
            Ac(ac) => ac.isotopic_composition(),
            Th(th) => th.isotopic_composition(),
            Pa(pa) => pa.isotopic_composition(),
            U(u) => u.isotopic_composition(),
            Np(np) => np.isotopic_composition(),
            Pu(pu) => pu.isotopic_composition(),
            Am(am) => am.isotopic_composition(),
            Cm(cm) => cm.isotopic_composition(),
            Bk(bk) => bk.isotopic_composition(),
            Cf(cf) => cf.isotopic_composition(),
            Es(es) => es.isotopic_composition(),
            Fm(fm) => fm.isotopic_composition(),
            Md(md) => md.isotopic_composition(),
            No(no) => no.isotopic_composition(),
            Lr(lr) => lr.isotopic_composition(),
            Rf(rf) => rf.isotopic_composition(),
            Db(db) => db.isotopic_composition(),
            Sg(sg) => sg.isotopic_composition(),
            Bh(bh) => bh.isotopic_composition(),
            Hs(hs) => hs.isotopic_composition(),
            Mt(mt) => mt.isotopic_composition(),
            Ds(ds) => ds.isotopic_composition(),
            Rg(rg) => rg.isotopic_composition(),
            Cn(cn) => cn.isotopic_composition(),
            Nh(nh) => nh.isotopic_composition(),
            Fl(fl) => fl.isotopic_composition(),
            Mc(mc) => mc.isotopic_composition(),
            Lv(lv) => lv.isotopic_composition(),
            Ts(ts) => ts.isotopic_composition(),
            Og(og) => og.isotopic_composition(),
        }
    }

    /// Mass number
    #[must_use]
    pub const fn mass_number(&self) -> usize {
        match self {
            H(h) => h.mass_number(),
            He(he) => he.mass_number(),
            Li(li) => li.mass_number(),
            Be(be) => be.mass_number(),
            B(b) => b.mass_number(),
            C(c) => c.mass_number(),
            N(n) => n.mass_number(),
            O(o) => o.mass_number(),
            F(f) => f.mass_number(),
            Ne(ne) => ne.mass_number(),
            Na(na) => na.mass_number(),
            Mg(mg) => mg.mass_number(),
            Al(al) => al.mass_number(),
            Si(si) => si.mass_number(),
            P(p) => p.mass_number(),
            S(s) => s.mass_number(),
            Cl(cl) => cl.mass_number(),
            Ar(ar) => ar.mass_number(),
            K(k) => k.mass_number(),
            Ca(ca) => ca.mass_number(),
            Sc(sc) => sc.mass_number(),
            Ti(ti) => ti.mass_number(),
            V(v) => v.mass_number(),
            Cr(cr) => cr.mass_number(),
            Mn(mn) => mn.mass_number(),
            Fe(fe) => fe.mass_number(),
            Co(co) => co.mass_number(),
            Ni(ni) => ni.mass_number(),
            Cu(cu) => cu.mass_number(),
            Zn(zn) => zn.mass_number(),
            Ga(ga) => ga.mass_number(),
            Ge(ge) => ge.mass_number(),
            As(r#as) => r#as.mass_number(),
            Se(se) => se.mass_number(),
            Br(br) => br.mass_number(),
            Kr(kr) => kr.mass_number(),
            Rb(rb) => rb.mass_number(),
            Sr(sr) => sr.mass_number(),
            Y(y) => y.mass_number(),
            Zr(zr) => zr.mass_number(),
            Nb(nb) => nb.mass_number(),
            Mo(mo) => mo.mass_number(),
            Tc(tc) => tc.mass_number(),
            Ru(ru) => ru.mass_number(),
            Rh(rh) => rh.mass_number(),
            Pd(pd) => pd.mass_number(),
            Ag(ag) => ag.mass_number(),
            Cd(cd) => cd.mass_number(),
            In(r#in) => r#in.mass_number(),
            Sn(sn) => sn.mass_number(),
            Sb(sb) => sb.mass_number(),
            Te(te) => te.mass_number(),
            I(i) => i.mass_number(),
            Xe(xe) => xe.mass_number(),
            Cs(cs) => cs.mass_number(),
            Ba(ba) => ba.mass_number(),
            La(la) => la.mass_number(),
            Ce(ce) => ce.mass_number(),
            Pr(pr) => pr.mass_number(),
            Nd(nd) => nd.mass_number(),
            Pm(pm) => pm.mass_number(),
            Sm(sm) => sm.mass_number(),
            Eu(eu) => eu.mass_number(),
            Gd(gd) => gd.mass_number(),
            Tb(tb) => tb.mass_number(),
            Dy(dy) => dy.mass_number(),
            Ho(ho) => ho.mass_number(),
            Er(er) => er.mass_number(),
            Tm(tm) => tm.mass_number(),
            Yb(yb) => yb.mass_number(),
            Lu(lu) => lu.mass_number(),
            Hf(hf) => hf.mass_number(),
            Ta(ta) => ta.mass_number(),
            W(w) => w.mass_number(),
            Re(re) => re.mass_number(),
            Os(os) => os.mass_number(),
            Ir(ir) => ir.mass_number(),
            Pt(pt) => pt.mass_number(),
            Au(au) => au.mass_number(),
            Hg(hg) => hg.mass_number(),
            Tl(tl) => tl.mass_number(),
            Pb(pb) => pb.mass_number(),
            Bi(bi) => bi.mass_number(),
            Po(po) => po.mass_number(),
            At(at) => at.mass_number(),
            Rn(rn) => rn.mass_number(),
            Fr(fr) => fr.mass_number(),
            Ra(ra) => ra.mass_number(),
            Ac(ac) => ac.mass_number(),
            Th(th) => th.mass_number(),
            Pa(pa) => pa.mass_number(),
            U(u) => u.mass_number(),
            Np(np) => np.mass_number(),
            Pu(pu) => pu.mass_number(),
            Am(am) => am.mass_number(),
            Cm(cm) => cm.mass_number(),
            Bk(bk) => bk.mass_number(),
            Cf(cf) => cf.mass_number(),
            Es(es) => es.mass_number(),
            Fm(fm) => fm.mass_number(),
            Md(md) => md.mass_number(),
            No(no) => no.mass_number(),
            Lr(lr) => lr.mass_number(),
            Rf(rf) => rf.mass_number(),
            Db(db) => db.mass_number(),
            Sg(sg) => sg.mass_number(),
            Bh(bh) => bh.mass_number(),
            Hs(hs) => hs.mass_number(),
            Mt(mt) => mt.mass_number(),
            Ds(ds) => ds.mass_number(),
            Rg(rg) => rg.mass_number(),
            Cn(cn) => cn.mass_number(),
            Nh(nh) => nh.mass_number(),
            Fl(fl) => fl.mass_number(),
            Mc(mc) => mc.mass_number(),
            Lv(lv) => lv.mass_number(),
            Ts(ts) => ts.mass_number(),
            Og(og) => og.mass_number(),
        }
    }

    /// Relative atomic mass
    #[must_use]
    pub const fn relative_atomic_mass(&self) -> Uncertain {
        match self {
            H(h) => h.relative_atomic_mass(),
            He(he) => he.relative_atomic_mass(),
            Li(li) => li.relative_atomic_mass(),
            Be(be) => be.relative_atomic_mass(),
            B(b) => b.relative_atomic_mass(),
            C(c) => c.relative_atomic_mass(),
            N(n) => n.relative_atomic_mass(),
            O(o) => o.relative_atomic_mass(),
            F(f) => f.relative_atomic_mass(),
            Ne(ne) => ne.relative_atomic_mass(),
            Na(na) => na.relative_atomic_mass(),
            Mg(mg) => mg.relative_atomic_mass(),
            Al(al) => al.relative_atomic_mass(),
            Si(si) => si.relative_atomic_mass(),
            P(p) => p.relative_atomic_mass(),
            S(s) => s.relative_atomic_mass(),
            Cl(cl) => cl.relative_atomic_mass(),
            Ar(ar) => ar.relative_atomic_mass(),
            K(k) => k.relative_atomic_mass(),
            Ca(ca) => ca.relative_atomic_mass(),
            Sc(sc) => sc.relative_atomic_mass(),
            Ti(ti) => ti.relative_atomic_mass(),
            V(v) => v.relative_atomic_mass(),
            Cr(cr) => cr.relative_atomic_mass(),
            Mn(mn) => mn.relative_atomic_mass(),
            Fe(fe) => fe.relative_atomic_mass(),
            Co(co) => co.relative_atomic_mass(),
            Ni(ni) => ni.relative_atomic_mass(),
            Cu(cu) => cu.relative_atomic_mass(),
            Zn(zn) => zn.relative_atomic_mass(),
            Ga(ga) => ga.relative_atomic_mass(),
            Ge(ge) => ge.relative_atomic_mass(),
            As(r#as) => r#as.relative_atomic_mass(),
            Se(se) => se.relative_atomic_mass(),
            Br(br) => br.relative_atomic_mass(),
            Kr(kr) => kr.relative_atomic_mass(),
            Rb(rb) => rb.relative_atomic_mass(),
            Sr(sr) => sr.relative_atomic_mass(),
            Y(y) => y.relative_atomic_mass(),
            Zr(zr) => zr.relative_atomic_mass(),
            Nb(nb) => nb.relative_atomic_mass(),
            Mo(mo) => mo.relative_atomic_mass(),
            Tc(tc) => tc.relative_atomic_mass(),
            Ru(ru) => ru.relative_atomic_mass(),
            Rh(rh) => rh.relative_atomic_mass(),
            Pd(pd) => pd.relative_atomic_mass(),
            Ag(ag) => ag.relative_atomic_mass(),
            Cd(cd) => cd.relative_atomic_mass(),
            In(r#in) => r#in.relative_atomic_mass(),
            Sn(sn) => sn.relative_atomic_mass(),
            Sb(sb) => sb.relative_atomic_mass(),
            Te(te) => te.relative_atomic_mass(),
            I(i) => i.relative_atomic_mass(),
            Xe(xe) => xe.relative_atomic_mass(),
            Cs(cs) => cs.relative_atomic_mass(),
            Ba(ba) => ba.relative_atomic_mass(),
            La(la) => la.relative_atomic_mass(),
            Ce(ce) => ce.relative_atomic_mass(),
            Pr(pr) => pr.relative_atomic_mass(),
            Nd(nd) => nd.relative_atomic_mass(),
            Pm(pm) => pm.relative_atomic_mass(),
            Sm(sm) => sm.relative_atomic_mass(),
            Eu(eu) => eu.relative_atomic_mass(),
            Gd(gd) => gd.relative_atomic_mass(),
            Tb(tb) => tb.relative_atomic_mass(),
            Dy(dy) => dy.relative_atomic_mass(),
            Ho(ho) => ho.relative_atomic_mass(),
            Er(er) => er.relative_atomic_mass(),
            Tm(tm) => tm.relative_atomic_mass(),
            Yb(yb) => yb.relative_atomic_mass(),
            Lu(lu) => lu.relative_atomic_mass(),
            Hf(hf) => hf.relative_atomic_mass(),
            Ta(ta) => ta.relative_atomic_mass(),
            W(w) => w.relative_atomic_mass(),
            Re(re) => re.relative_atomic_mass(),
            Os(os) => os.relative_atomic_mass(),
            Ir(ir) => ir.relative_atomic_mass(),
            Pt(pt) => pt.relative_atomic_mass(),
            Au(au) => au.relative_atomic_mass(),
            Hg(hg) => hg.relative_atomic_mass(),
            Tl(tl) => tl.relative_atomic_mass(),
            Pb(pb) => pb.relative_atomic_mass(),
            Bi(bi) => bi.relative_atomic_mass(),
            Po(po) => po.relative_atomic_mass(),
            At(at) => at.relative_atomic_mass(),
            Rn(rn) => rn.relative_atomic_mass(),
            Fr(fr) => fr.relative_atomic_mass(),
            Ra(ra) => ra.relative_atomic_mass(),
            Ac(ac) => ac.relative_atomic_mass(),
            Th(th) => th.relative_atomic_mass(),
            Pa(pa) => pa.relative_atomic_mass(),
            U(u) => u.relative_atomic_mass(),
            Np(np) => np.relative_atomic_mass(),
            Pu(pu) => pu.relative_atomic_mass(),
            Am(am) => am.relative_atomic_mass(),
            Cm(cm) => cm.relative_atomic_mass(),
            Bk(bk) => bk.relative_atomic_mass(),
            Cf(cf) => cf.relative_atomic_mass(),
            Es(es) => es.relative_atomic_mass(),
            Fm(fm) => fm.relative_atomic_mass(),
            Md(md) => md.relative_atomic_mass(),
            No(no) => no.relative_atomic_mass(),
            Lr(lr) => lr.relative_atomic_mass(),
            Rf(rf) => rf.relative_atomic_mass(),
            Db(db) => db.relative_atomic_mass(),
            Sg(sg) => sg.relative_atomic_mass(),
            Bh(bh) => bh.relative_atomic_mass(),
            Hs(hs) => hs.relative_atomic_mass(),
            Mt(mt) => mt.relative_atomic_mass(),
            Ds(ds) => ds.relative_atomic_mass(),
            Rg(rg) => rg.relative_atomic_mass(),
            Cn(cn) => cn.relative_atomic_mass(),
            Nh(nh) => nh.relative_atomic_mass(),
            Fl(fl) => fl.relative_atomic_mass(),
            Mc(mc) => mc.relative_atomic_mass(),
            Lv(lv) => lv.relative_atomic_mass(),
            Ts(ts) => ts.relative_atomic_mass(),
            Og(og) => og.relative_atomic_mass(),
        }
    }

    /// Symbol
    #[must_use]
    pub const fn symbol(&self) -> &'static str {
        match self {
            H(H::Two) => "D",
            H(H::Three) => "T",
            isotope => isotope.element().symbol(),
        }
    }
}

impl From<Isotope> for Element {
    fn from(value: Isotope) -> Self {
        value.element()
    }
}

impl FromStr for Isotope {
    type Err = Error;

    fn from_str(value: &str) -> Result<Self> {
        match value {
            "H" => Ok(H(H::iter().max_by_key(H::isotopic_composition).unwrap())),
            "He" => Ok(He(He::iter().max_by_key(He::isotopic_composition).unwrap())),
            "Li" => Ok(Li(Li::iter().max_by_key(Li::isotopic_composition).unwrap())),
            "Be" => Ok(Be(Be::iter().next().unwrap())),
            "B" => Ok(B(B::iter().max_by_key(B::isotopic_composition).unwrap())),
            "C" => Ok(C(C::iter().max_by_key(C::isotopic_composition).unwrap())),
            "N" => Ok(N(N::iter().max_by_key(N::isotopic_composition).unwrap())),
            "O" => Ok(O(O::iter().max_by_key(O::isotopic_composition).unwrap())),
            "F" => Ok(F(F::iter().next().unwrap())),
            "Ne" => Ok(Ne(Ne::iter().max_by_key(Ne::isotopic_composition).unwrap())),
            "Na" => Ok(Na(Na::iter().next().unwrap())),
            "Mg" => Ok(Mg(Mg::iter().max_by_key(Mg::isotopic_composition).unwrap())),
            "Al" => Ok(Al(Al::iter().next().unwrap())),
            "Si" => Ok(Si(Si::iter().max_by_key(Si::isotopic_composition).unwrap())),
            "P" => Ok(P(P::iter().next().unwrap())),
            "S" => Ok(S(S::iter().max_by_key(S::isotopic_composition).unwrap())),
            "Cl" => Ok(Cl(Cl::iter().max_by_key(Cl::isotopic_composition).unwrap())),
            "Ar" => Ok(Ar(Ar::iter().max_by_key(Ar::isotopic_composition).unwrap())),
            "K" => Ok(K(K::iter().max_by_key(K::isotopic_composition).unwrap())),
            "Ca" => Ok(Ca(Ca::iter().max_by_key(Ca::isotopic_composition).unwrap())),
            "Sc" => Ok(Sc(Sc::iter().next().unwrap())),
            "Ti" => Ok(Ti(Ti::iter().max_by_key(Ti::isotopic_composition).unwrap())),
            "V" => Ok(V(V::iter().max_by_key(V::isotopic_composition).unwrap())),
            "Cr" => Ok(Cr(Cr::iter().max_by_key(Cr::isotopic_composition).unwrap())),
            "Mn" => Ok(Mn(Mn::iter().next().unwrap())),
            "Fe" => Ok(Fe(Fe::iter().max_by_key(Fe::isotopic_composition).unwrap())),
            "Co" => Ok(Co(Co::iter().next().unwrap())),
            "Ni" => Ok(Ni(Ni::iter().max_by_key(Ni::isotopic_composition).unwrap())),
            "Cu" => Ok(Cu(Cu::iter().max_by_key(Cu::isotopic_composition).unwrap())),
            "Zn" => Ok(Zn(Zn::iter().max_by_key(Zn::isotopic_composition).unwrap())),
            "Ga" => Ok(Ga(Ga::iter().max_by_key(Ga::isotopic_composition).unwrap())),
            "Ge" => Ok(Ge(Ge::iter().max_by_key(Ge::isotopic_composition).unwrap())),
            "As" => Ok(As(As::iter().next().unwrap())),
            "Se" => Ok(Se(Se::iter().max_by_key(Se::isotopic_composition).unwrap())),
            "Br" => Ok(Br(Br::iter().max_by_key(Br::isotopic_composition).unwrap())),
            "Kr" => Ok(Kr(Kr::iter().max_by_key(Kr::isotopic_composition).unwrap())),
            "Rb" => Ok(Rb(Rb::iter().max_by_key(Rb::isotopic_composition).unwrap())),
            "Sr" => Ok(Sr(Sr::iter().max_by_key(Sr::isotopic_composition).unwrap())),
            "Y" => Ok(Y(Y::iter().next().unwrap())),
            "Zr" => Ok(Zr(Zr::iter().max_by_key(Zr::isotopic_composition).unwrap())),
            "Nb" => Ok(Nb(Nb::iter().next().unwrap())),
            "Mo" => Ok(Mo(Mo::iter().max_by_key(Mo::isotopic_composition).unwrap())),
            "Tc" => Ok(Tc(Tc::iter().max_by_key(Tc::isotopic_composition).unwrap())),
            "Ru" => Ok(Ru(Ru::iter().max_by_key(Ru::isotopic_composition).unwrap())),
            "Rh" => Ok(Rh(Rh::iter().next().unwrap())),
            "Pd" => Ok(Pd(Pd::iter().max_by_key(Pd::isotopic_composition).unwrap())),
            "Ag" => Ok(Ag(Ag::iter().max_by_key(Ag::isotopic_composition).unwrap())),
            "Cd" => Ok(Cd(Cd::iter().max_by_key(Cd::isotopic_composition).unwrap())),
            "In" => Ok(In(In::iter().max_by_key(In::isotopic_composition).unwrap())),
            "Sn" => Ok(Sn(Sn::iter().max_by_key(Sn::isotopic_composition).unwrap())),
            "Sb" => Ok(Sb(Sb::iter().max_by_key(Sb::isotopic_composition).unwrap())),
            "Te" => Ok(Te(Te::iter().max_by_key(Te::isotopic_composition).unwrap())),
            "I" => Ok(I(I::iter().next().unwrap())),
            "Xe" => Ok(Xe(Xe::iter().max_by_key(Xe::isotopic_composition).unwrap())),
            "Cs" => Ok(Cs(Cs::iter().next().unwrap())),
            "Ba" => Ok(Ba(Ba::iter().max_by_key(Ba::isotopic_composition).unwrap())),
            "La" => Ok(La(La::iter().max_by_key(La::isotopic_composition).unwrap())),
            "Ce" => Ok(Ce(Ce::iter().max_by_key(Ce::isotopic_composition).unwrap())),
            "Pr" => Ok(Pr(Pr::iter().next().unwrap())),
            "Nd" => Ok(Nd(Nd::iter().max_by_key(Nd::isotopic_composition).unwrap())),
            "Pm" => Ok(Pm(Pm::iter().max_by_key(Pm::isotopic_composition).unwrap())),
            "Sm" => Ok(Sm(Sm::iter().max_by_key(Sm::isotopic_composition).unwrap())),
            "Eu" => Ok(Eu(Eu::iter().max_by_key(Eu::isotopic_composition).unwrap())),
            "Gd" => Ok(Gd(Gd::iter().max_by_key(Gd::isotopic_composition).unwrap())),
            "Tb" => Ok(Tb(Tb::iter().next().unwrap())),
            "Dy" => Ok(Dy(Dy::iter().max_by_key(Dy::isotopic_composition).unwrap())),
            "Ho" => Ok(Ho(Ho::iter().next().unwrap())),
            "Er" => Ok(Er(Er::iter().max_by_key(Er::isotopic_composition).unwrap())),
            "Tm" => Ok(Tm(Tm::iter().next().unwrap())),
            "Yb" => Ok(Yb(Yb::iter().max_by_key(Yb::isotopic_composition).unwrap())),
            "Lu" => Ok(Lu(Lu::iter().max_by_key(Lu::isotopic_composition).unwrap())),
            "Hf" => Ok(Hf(Hf::iter().max_by_key(Hf::isotopic_composition).unwrap())),
            "Ta" => Ok(Ta(Ta::iter().max_by_key(Ta::isotopic_composition).unwrap())),
            "W" => Ok(W(W::iter().max_by_key(W::isotopic_composition).unwrap())),
            "Re" => Ok(Re(Re::iter().max_by_key(Re::isotopic_composition).unwrap())),
            "Os" => Ok(Os(Os::iter().max_by_key(Os::isotopic_composition).unwrap())),
            "Ir" => Ok(Ir(Ir::iter().max_by_key(Ir::isotopic_composition).unwrap())),
            "Pt" => Ok(Pt(Pt::iter().max_by_key(Pt::isotopic_composition).unwrap())),
            "Au" => Ok(Au(Au::iter().next().unwrap())),
            "Hg" => Ok(Hg(Hg::iter().max_by_key(Hg::isotopic_composition).unwrap())),
            "Tl" => Ok(Tl(Tl::iter().max_by_key(Tl::isotopic_composition).unwrap())),
            "Pb" => Ok(Pb(Pb::iter().max_by_key(Pb::isotopic_composition).unwrap())),
            "Bi" => Ok(Bi(Bi::iter().next().unwrap())),
            "Po" => Ok(Po(Po::iter().max_by_key(Po::isotopic_composition).unwrap())),
            "At" => Ok(At(At::iter().max_by_key(At::isotopic_composition).unwrap())),
            "Rn" => Ok(Rn(Rn::iter().max_by_key(Rn::isotopic_composition).unwrap())),
            "Fr" => Ok(Fr(Fr::iter().next().unwrap())),
            "Ra" => Ok(Ra(Ra::iter().max_by_key(Ra::isotopic_composition).unwrap())),
            "Ac" => Ok(Ac(Ac::iter().next().unwrap())),
            "Th" => Ok(Th(Th::iter().max_by_key(Th::isotopic_composition).unwrap())),
            "Pa" => Ok(Pa(Pa::iter().next().unwrap())),
            "U" => Ok(U(U::iter().max_by_key(U::isotopic_composition).unwrap())),
            "Np" => Ok(Np(Np::iter().max_by_key(Np::isotopic_composition).unwrap())),
            "Pu" => Ok(Pu(Pu::iter().max_by_key(Pu::isotopic_composition).unwrap())),
            "Am" => Ok(Am(Am::iter().max_by_key(Am::isotopic_composition).unwrap())),
            "Cm" => Ok(Cm(Cm::iter().max_by_key(Cm::isotopic_composition).unwrap())),
            "Bk" => Ok(Bk(Bk::iter().max_by_key(Bk::isotopic_composition).unwrap())),
            "Cf" => Ok(Cf(Cf::iter().max_by_key(Cf::isotopic_composition).unwrap())),
            "Es" => Ok(Es(Es::iter().next().unwrap())),
            "Fm" => Ok(Fm(Fm::iter().next().unwrap())),
            "Md" => Ok(Md(Md::iter().max_by_key(Md::isotopic_composition).unwrap())),
            "No" => Ok(No(No::iter().next().unwrap())),
            "Lr" => Ok(Lr(Lr::iter().next().unwrap())),
            "Rf" => Ok(Rf(Rf::iter().next().unwrap())),
            "Db" => Ok(Db(Db::iter().next().unwrap())),
            "Sg" => Ok(Sg(Sg::iter().next().unwrap())),
            "Bh" => Ok(Bh(Bh::iter().next().unwrap())),
            "Hs" => Ok(Hs(Hs::iter().next().unwrap())),
            "Mt" => Ok(Mt(Mt::iter().next().unwrap())),
            "Ds" => Ok(Ds(Ds::iter().next().unwrap())),
            "Rg" => Ok(Rg(Rg::iter().next().unwrap())),
            "Cn" => Ok(Cn(Cn::iter().next().unwrap())),
            "Nh" => Ok(Nh(Nh::iter().next().unwrap())),
            "Fl" => Ok(Fl(Fl::iter().next().unwrap())),
            "Mc" => Ok(Mc(Mc::iter().next().unwrap())),
            "Lv" => Ok(Lv(Lv::iter().next().unwrap())),
            "Ts" => Ok(Ts(Ts::iter().next().unwrap())),
            "Og" => Ok(Og(Og::iter().next().unwrap())),
            _ => Err(Error::Parse),
        }
    }
}

// /// Measurement
// pub trait Measurement {
//     fn minimum(&self) -> f64;
//     fn medium(&self) -> f64;
//     fn maximum(&self) -> f64;
// }
// impl Measurement for Uncertain {
//     fn minimum(&self) -> f64 {
//         self.minimum()
//     }
//     fn medium(&self) -> f64 {
//         self.medium()
//     }
//     fn maximum(&self) -> f64 {
//         self.maximum()
//     }
// }

/// Notes
///
/// Notes for Representative Isotopic Composition and Standard Atomic Weight.
///
/// - g - Geological materials are known in which the element has an isotopic
///   composition outside the limits for normal material. The difference between
///   the atomic weight of the element in such materials and that given in the
///   table may exceed the stated uncertainty.
/// - m - Modified isotopic compositions may be found in commercially available
///   material because the material has been subjected to an undisclosed or
///   inadvertent isotopic fractionation. Substantial deviations in atomic
///   weight of the element from that given in the table can occur.
/// - r - Range in isotopic composition of normal terrestrial material prevents
///   a more precise standard atomic weight being given; the tabulated
///   atomic-weight value and uncertainty should be applicable to normal
///   materials.
pub enum Notes {
    G,
    M,
    R,
}
